In [52]:
import os, sys
import numpy as np

def getinfo(file):
    buff=file.split("_")
    run=int(buff[1].split('run')[1])
    time = int(buff[2].split('.')[0])
    return [run, time]
    
info = np.array([ getinfo(file) for file in os.listdir( "../calibrationdb/" ) if "csv" in file ])
mint=np.min(info[:,1])
info = np.insert( info,2, (info[:,1]-mint)/(3600*24), axis=1 )
print(info)

[[      5076 1614300226         48]
 [      4886 1613074636         34]
 [      4986 1613690547         41]
 [      7115 1637013221        311]
 [      7033 1636156756        301]
 [      6732 1632175995        255]
 [      6628 1630886487        240]
 [      6603 1630450100        235]
 [      6468 1628632260        214]
 [      5092 1614550524         51]
 [      5457 1617648069         87]
 [      5635 1619133315        104]
 [      6719 1631921486        252]
 [      7210 1637788392        320]
 [      6036 1623603606        156]
 [      6555 1629323269        222]
 [      6608 1630531577        236]
 [      6736 1632274166        257]
 [      6641 1631138651        243]
 [      4734 1612389343         26]
 [      4632 1611795400         19]
 [      5125 1614813271         54]
 [      5260 1616014922         68]
 [      5390 1616805688         77]
 [      5837 1620868987        125]
 [      5894 1621568782        133]
 [      5984 1622315494        141]
 [      6030 1623445835     